### ISSUE TITLE
Allow to filter on *different* metrics during scoring

### ISSUE THREAD

**Issue by lucventurini** [lucventurini/mikado#130]
Currently, when evaluating a metric for scoring, it is possible to specify conditions that would make Mikado assign to it a score of 0. For example, if we are considering the metric non_verified_introns_num, we cannot explicitly say that this metric should be ignored when the transcript is monoexonic.

A solution could be allowing expressions of the form:

```
non_verified_introns_num:
  rescaling: max
  multiplier: -10
  filter:
    operator: gt
    value: 1
    metric: exons_num
```

This would allow to filter based on **different metrics** than the one examined.
